apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: rawkp2dsw-python 
  janus-idp.io/tekton: rawkp2dsw-python
  backstage.io/kubernetes-id: rawkp2dsw-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: rawkp2dsw-python
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml