apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: rawkp2dsw-python
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/rhtap_qe/rhtap-qe-python:340c3f512e0d3ae0f6c0162d4b4158b0adecf45f@sha256:d8dd054e133e5204b74f09669279fe07aeaf0f94bfa035f3fb8bc718f12cca22
          name: container-image
