apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: rawkp2dsw-python
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: rawkp2dsw-python 
  name: rawkp2dsw-python
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: rawkp2dsw-python 
